# basedir = workflow.basedir
# print("Base dir: {}".format(basedir))

configfile: "/.........../public_analysis_lineages_workflow/config/config.yaml"

##### load rules #####
include: "rules/fetch_public_fasta.smk"
include: "rules/create_multifasta_public.smk"
include: "rules/run_pangolin.smk"
include: "rules/concat_csv.smk"
include: "rules/symlink.smk"

##### target rules ######
rule all:
	input: expand("{output_dir}/pango/symlinked.txt", output_dir=config["output_dir"])
