[ERAPRO_DETAILS]
host = 
port = 
serviceName = 
userName = 
password = 

[ENAPRO_DETAILS]
host = 
port = 
serviceName = 
userName = 
password = 

[EMAIL_DETAILS]
sender_email_add = 
sender_email_pass = 
emails_list = 
