# basedir = workflow.basedir
# print("Base dir: {}".format(basedir))

configfile: "/......./private_analysis_lineages_workflow/config/config.yaml"

##### load rules #####
include: "rules/fetch_private_fasta.smk"
include: "rules/create_multifasta.smk"
include: "rules/run_pangolin.smk"
include: "rules/concat_csv.smk"
include:"rules/transfer.smk"

##### target rules ######
rule all:
	input: expand("{output_dir}/end.txt", output_dir=config["output_dir"])
